### ISSUE TITLE
no ref available for saving qr code

### ISSUE THREAD

**Issue by loekTheDreamer** [exzos28/react-native-qrcode-svg#4]
How do I save the qr code to file without having access to the content?

normally i would do something like :

Ref={(c) => (qrCodeRef.current = c)}
and then  qrCodeRef.current?.toDataURL... using RNFS

please assist?

**Comment by exzos28** [comment]
@loekTheDreamer Hi there! Please, provide more info about "toDataURL..." method.

**Comment by loekTheDreamer** [comment]
from this library react-native-qrcode-svg
[react-native-qrcode-svg](https://www.npmjs.com/package/react-native-qrcode-svg#saving-generated-code-to-gallery)
```javascript
  saveQrToDisk() {
   	this.svg.toDataURL((data) => {
   		RNFS.writeFile(RNFS.CachesDirectoryPath+"/some-name.png", data, 'base64')
   		  .then((success) => {
   			  return CameraRoll.saveToCameraRoll(RNFS.CachesDirectoryPath+"/some-name.png", 'photo')
   		  })
   		  .then(() => {
   			  this.setState({ busy: false, imageSaved: true  })
   			  ToastAndroid.show('Saved to gallery !!', ToastAndroid.SHORT)
   		  })
   	})
  }
```

we decided to switch to yours becasue it is more compatible with android cameras than other packages

**Comment by exzos28** [comment]
@loekTheDreamer I would rather use [that library](https://github.com/gre/react-native-view-shot) than work with base64

**Comment by loekTheDreamer** [comment]
Thank you, i was about to try that next.
